version: "3.9"

services:
  post-service-app:
    build:
      context: .
      dockerfile: /src/services/PostService/PostService.API/Dockerfile
    depends_on:
      - postgresql-db
      - kafka
      - elk
      - post-redis

  postgresql-db:
    image: postgres:latest

  identity-service-app:
    build:
      context: .
      dockerfile: /src/services/IdentityService/IdentityService.PL/Dockerfile
    depends_on:
      - mssqlserver-db
      - kafka
      - elk
      - identity-redis

  mssqlserver-db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  chat-service-app:
    build:
      context: .
      dockerfile: /src/services/ChatService/ChatService.API/Dockerfile
    depends_on:
      - mongo-db
      - kafka
      - elk
      - chat-redis

  mongo-db:
    image: mongo

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper

  elk:
    image: sebp/elk

  post-redis:
    image: redis:latest

  identity-redis:
    image: redis:latest

  chat-redis:
    image: redis:latest
